addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints: []
kind: EndpointSlice
metadata:
  labels:
    app.kubernetes.io/managed-by: kubeaid
    app.kubernetes.io/name: etcd
    kubernetes.io/service-name: etcd
  name: etcd
  namespace: kube-system
ports:
- name: metrics
  port: 2381
  protocol: TCP
